# k8s/secrets.yaml

# 1. The Database Vault
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  # Kubernetes will securely inject these into our Go apps
  username: iicpc_admin
  password: supersecretpassword
  url: "postgresql://iicpc_admin:supersecretpassword@timescaledb-service:5432/metrics_db"

---

# 2. The Redis Vault
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
stringData:
  url: "redis://redis-service:6379"