apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 2 # We can scale this up to handle massive order volume!
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
      - name: telemetry
        image: iicpc-platform:latest # Standardized image name
        command: ["./telemetry-binary"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: "timescaledb-service" 
        - name: REDPANDA_HOST
          value: "redpanda-service:9092"
        # Pull credentials securely from our K8s Vault
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        # Set strict CPU and Memory budgets
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"