// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sandbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 2. The Request Payload
type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	SourceFilePath string                 `protobuf:"bytes,2,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"` // e.g., "/tmp/submission-183749.go"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ExecuteRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

// 3. The Response Payload
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ContainerIp   string                 `protobuf:"bytes,3,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`        // The IP where the trading engine is listening
	ContainerPort int32                  `protobuf:"varint,4,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"` // The port mapped by Docker (e.g., 32768)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *ExecuteResponse) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

var File_proto_sandbox_proto protoreflect.FileDescriptor

const file_proto_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sandbox.proto\x12\asandbox\"_\n" +
	"\x0eExecuteRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12(\n" +
	"\x10source_file_path\x18\x02 \x01(\tR\x0esourceFilePath\"\x8f\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcontainer_ip\x18\x03 \x01(\tR\vcontainerIp\x12%\n" +
	"\x0econtainer_port\x18\x04 \x01(\x05R\rcontainerPort2X\n" +
	"\x0eSandboxService\x12F\n" +
	"\x11ExecuteSubmission\x12\x17.sandbox.ExecuteRequest\x1a\x18.sandbox.ExecuteResponseB\x13Z\x11iicpc-platform/pbb\x06proto3"

var (
	file_proto_sandbox_proto_rawDescOnce sync.Once
	file_proto_sandbox_proto_rawDescData []byte
)

func file_proto_sandbox_proto_rawDescGZIP() []byte {
	file_proto_sandbox_proto_rawDescOnce.Do(func() {
		file_proto_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)))
	})
	return file_proto_sandbox_proto_rawDescData
}

var file_proto_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sandbox_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: sandbox.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: sandbox.ExecuteResponse
}
var file_proto_sandbox_proto_depIdxs = []int32{
	0, // 0: sandbox.SandboxService.ExecuteSubmission:input_type -> sandbox.ExecuteRequest
	1, // 1: sandbox.SandboxService.ExecuteSubmission:output_type -> sandbox.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sandbox_proto_init() }
func file_proto_sandbox_proto_init() {
	if File_proto_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sandbox_proto_goTypes,
		DependencyIndexes: file_proto_sandbox_proto_depIdxs,
		MessageInfos:      file_proto_sandbox_proto_msgTypes,
	}.Build()
	File_proto_sandbox_proto = out.File
	file_proto_sandbox_proto_goTypes = nil
	file_proto_sandbox_proto_depIdxs = nil
}
